from shared.gitmojis import GitmojiEnum

mojis = [
    {
        "type": "fix",
        "icon": GitmojiEnum.FIX,
        "code": ":bug:",
        "desc": "Fix a bug.",
    },
    {
        "type": "feat",
        "icon": GitmojiEnum.FEAT,
        "code": ":sparkles:",
        "desc": "Introduce new features.",
    },
    {
        "type": "docs",
        "icon": GitmojiEnum.DOCS,
        "code": ":memo:",
        "desc": "Add or update documentation.",
    },
    {
        "type": "style",
        "icon": GitmojiEnum.STYLE,
        "code": ":art:",
        "desc": "Improve structure / format of the code.",
    },
    {
        "type": "refactor",
        "icon": GitmojiEnum.REFACTOR,
        "code": ":recycle:",
        "desc": "Refactor code.",
    },
    {
        "type": "perf",
        "icon": GitmojiEnum.PERF,
        "code": ":zap:",
        "desc": "Improve performance.",
    },
    {
        "type": "test",
        "icon": GitmojiEnum.TEST,
        "code": ":white_check_mark:",
        "desc": "Add, update, or pass tests.",
    },
    {
        "type": "build",
        "icon": GitmojiEnum.BUILD,
        "code": ":construction_worker:",
        "desc": "Add or update CI build system.",
    },
    {
        "type": "ci",
        "icon": GitmojiEnum.CI,
        "code": ":green_heart:",
        "desc": "Fix CI Build.",
    },
    {
        "type": "revert",
        "icon": GitmojiEnum.REVERT,
        "code": ":rewind:",
        "desc": "Revert changes.",
    },
    {
        "type": "dump",
        "icon": GitmojiEnum.DUMP,
        "code": ":fire:",
        "desc": "Remove code or files.",
    },
    {
        "type": "hotfix",
        "icon": GitmojiEnum.HOTFIX,
        "code": ":ambulance:",
        "desc": "Critical hotfix.",
    },
    {
        "type": "deploy",
        "icon": GitmojiEnum.DEPLOY,
        "code": ":rocket:",
        "desc": "Deploy stuff.",
    },
    {
        "type": "ui",
        "icon": GitmojiEnum.UI,
        "code": ":lipstick:",
        "desc": "Add or update the UI and style files.",
    },
    {
        "type": "init",
        "icon": GitmojiEnum.INIT,
        "code": ":tada:",
        "desc": "Begin a project.",
    },
    {
        "type": "security",
        "icon": GitmojiEnum.SECURITY,
        "code": ":lock:",
        "desc": "Fix security issues.",
    },
    {
        "type": "secret",
        "icon": GitmojiEnum.SECRET,
        "code": ":closed_lock_with_key:",
        "desc": "Add or update secrets.",
    },
    {
        "type": "bump",
        "icon": GitmojiEnum.BUMP,
        "code": ":bookmark:",
        "desc": "Release / Version tags.",
    },
    {
        "type": "fix-lint",
        "icon": GitmojiEnum.FIX_LINT,
        "code": ":rotating_light:",
        "desc": "Fix compiler / linter warnings.",
    },
    {
        "type": "wip",
        "icon": GitmojiEnum.WIP,
        "code": ":construction:",
        "desc": "Work in progress.",
    },
    {
        "type": "dep-drop",
        "icon": GitmojiEnum.DEP_DROP,
        "code": ":arrow_down:",
        "desc": "Downgrade dependencies.",
    },
    {
        "type": "dep-bump",
        "icon": GitmojiEnum.DEP_BUMP,
        "code": ":arrow_up:",
        "desc": "Upgrade dependencies.",
    },
    {
        "type": "pin",
        "icon": GitmojiEnum.PIN,
        "code": ":pushpin:",
        "desc": "Pin dependencies to specific versions.",
    },
    {
        "type": "analytics",
        "icon": GitmojiEnum.ANALYTICS,
        "code": ":chart_with_upwards_trend:",
        "desc": "Add or update analytics or track code.",
    },
    {
        "type": "dep-add",
        "icon": GitmojiEnum.DEP_ADD,
        "code": ":heavy_plus_sign:",
        "desc": "Add a dependency.",
    },
    {
        "type": "dep-rm",
        "icon": GitmojiEnum.DEP_RM,
        "code": ":heavy_minus_sign:",
        "desc": "Remove a dependency.",
    },
    {
        "type": "config",
        "icon": GitmojiEnum.CONFIG,
        "code": ":wrench:",
        "desc": "Add or update configuration files.",
    },
    {
        "type": "script",
        "icon": GitmojiEnum.SCRIPT,
        "code": ":hammer:",
        "desc": "Add or update development scripts.",
    },
    {
        "type": "lang",
        "icon": GitmojiEnum.LANG,
        "code": ":globe_with_meridians:",
        "desc": "Internationalization and localization.",
    },
    {
        "type": "typo",
        "icon": GitmojiEnum.TYPO,
        "code": ":pencil2:",
        "desc": "Fix typos.",
    },
    {
        "type": "poop",
        "icon": GitmojiEnum.POOP,
        "code": ":poop:",
        "desc": "Write bad code that needs to be improved.",
    },
    {
        "type": "merge",
        "icon": GitmojiEnum.MERGE,
        "code": ":twisted_rightwards_arrows:",
        "desc": "Merge branches.",
    },
    {
        "type": "package",
        "icon": GitmojiEnum.PACKAGE,
        "code": ":package:",
        "desc": "Add or update compiled files or packages.",
    },
    {
        "type": "external",
        "icon": GitmojiEnum.EXTERNAL,
        "code": ":alien:",
        "desc": "Update code due to external API changes.",
    },
    {
        "type": "resource",
        "icon": GitmojiEnum.RESOURCE,
        "code": ":truck:",
        "desc": "Move or rename resources (e.g.: files, paths, routes).",
    },
    {
        "type": "license",
        "icon": GitmojiEnum.LICENSE,
        "code": ":page_facing_up:",
        "desc": "Add or update license.",
    },
    {
        "type": "boom",
        "icon": GitmojiEnum.BOOM,
        "code": ":boom:",
        "desc": "Introduce breaking changes.",
    },
    {
        "type": "asset",
        "icon": GitmojiEnum.ASSET,
        "code": ":bento:",
        "desc": "Add or update assets.",
    },
    {
        "type": "accessibility",
        "icon": GitmojiEnum.ACCESSIBILITY,
        "code": ":wheelchair:",
        "desc": "Improve accessibility.",
    },
    {
        "type": "source-docs",
        "icon": GitmojiEnum.SOURCE_DOCS,
        "code": ":bulb:",
        "desc": "Add or update comments in source code.",
    },
    {
        "type": "beer",
        "icon": GitmojiEnum.BEER,
        "code": ":beers:",
        "desc": "Write code drunkenly.",
    },
    {
        "type": "text",
        "icon": GitmojiEnum.TEXT,
        "code": ":speech_balloon:",
        "desc": "Add or update text and literals.",
    },
    {
        "type": "db",
        "icon": GitmojiEnum.DB,
        "code": ":card_file_box:",
        "desc": "Perform database related changes.",
    },
    {
        "type": "logs-add",
        "icon": GitmojiEnum.LOGS_ADD,
        "code": ":loud_sound:",
        "desc": "Add or update logs.",
    },
    {
        "type": "logs-rm",
        "icon": GitmojiEnum.LOGS_RM,
        "code": ":mute:",
        "desc": "Remove logs.",
    },
    {
        "type": "people",
        "icon": GitmojiEnum.PEOPLE,
        "code": ":busts_in_silhouette:",
        "desc": "Add or update contributor(s).",
    },
    {
        "type": "ux",
        "icon": GitmojiEnum.UX,
        "code": ":children_crossing:",
        "desc": "Improve user experience / usability.",
    },
    {
        "type": "arch",
        "icon": GitmojiEnum.ARCH,
        "code": ":building_construction:",
        "desc": "Make architectural changes.",
    },
    {
        "type": "design",
        "icon": GitmojiEnum.DESIGN,
        "code": ":iphone:",
        "desc": "Work on responsive design.",
    },
    {
        "type": "mock",
        "icon": GitmojiEnum.MOCK,
        "code": ":clown_face:",
        "desc": "Mock things.",
    },
    {
        "type": "egg",
        "icon": GitmojiEnum.EGG,
        "code": ":egg:",
        "desc": "Add or update an easter egg.",
    },
    {
        "type": "ignore",
        "icon": GitmojiEnum.IGNORE,
        "code": ":see_no_evil:",
        "desc": "Add or update a .gitignore file.",
    },
    {
        "type": "snap",
        "icon": GitmojiEnum.SNAP,
        "code": ":camera_flash:",
        "desc": "Add or update snapshots.",
    },
    {
        "type": "experiment",
        "icon": GitmojiEnum.EXPERIMENT,
        "code": ":alembic:",
        "desc": "Perform experiments.",
    },
    {
        "type": "seo",
        "icon": GitmojiEnum.SEO,
        "code": ":mag:",
        "desc": "Improve SEO.",
    },
    {
        "type": "types",
        "icon": GitmojiEnum.TYPES,
        "code": ":label:",
        "desc": "Add or update types.",
    },
    {
        "type": "seed",
        "icon": GitmojiEnum.SEED,
        "code": ":seedling:",
        "desc": "Add or update seed files.",
    },
    {
        "type": "flag",
        "icon": GitmojiEnum.FLAG,
        "code": ":triangular_flag_on_post:",
        "desc": "Add, update, or remove feature flags.",
    },
    {
        "type": "catch",
        "icon": GitmojiEnum.CATCH,
        "code": ":goal_net:",
        "desc": "Catch errors.",
    },
    {
        "type": "animation",
        "icon": GitmojiEnum.ANIMATION,
        "code": ":dizzy:",
        "desc": "Add or update animations and transitions.",
    },
    {
        "type": "deprecation",
        "icon": GitmojiEnum.DEPRECATION,
        "code": ":wastebasket:",
        "desc": "Deprecate code that needs to be cleaned up.",
    },
    {
        "type": "auth",
        "icon": GitmojiEnum.AUTH,
        "code": ":passport_control:",
        "desc": "Work on code related to authorization, roles and permissions.",
    },
    {
        "type": "fix-simple",
        "icon": GitmojiEnum.FIX_SIMPLE,
        "code": ":adhesive_bandage:",
        "desc": "Simple fix for a non-critical issue.",
    },
    {
        "type": "exploration",
        "icon": GitmojiEnum.EXPLORATION,
        "code": ":monocle_face:",
        "desc": "Data exploration/inspection.",
    },
    {
        "type": "dead",
        "icon": GitmojiEnum.DEAD,
        "code": ":coffin:",
        "desc": "Remove dead code.",
    },
    {
        "type": "test-fail",
        "icon": GitmojiEnum.TEST_FAIL,
        "code": ":test_tube:",
        "desc": "Add a failing test.",
    },
    {
        "type": "logic",
        "icon": GitmojiEnum.LOGIC,
        "code": ":necktie:",
        "desc": "Add or update business logic.",
    },
    {
        "type": "health",
        "icon": GitmojiEnum.HEALTH,
        "code": ":stethoscope:",
        "desc": "Add or update healthcheck.",
    },
    {
        "type": "infra",
        "icon": GitmojiEnum.INFRA,
        "code": ":bricks:",
        "desc": "Infrastructure related changes.",
    },
    {
        "type": "devxp",
        "icon": GitmojiEnum.DEVXP,
        "code": ":technologist:",
        "desc": "Improve developer experience.",
    },
    {
        "type": "money",
        "icon": GitmojiEnum.MONEY,
        "code": ":money_with_wings:",
        "desc": "Add sponsorships or money related infrastructure.",
    },
    {
        "type": "threading",
        "icon": GitmojiEnum.THREADING,
        "code": ":thread:",
        "desc": "Add or update code related to multithreading or concurrency.",
    },
    {
        "type": "validation",
        "icon": GitmojiEnum.VALIDATION,
        "code": ":safety_vest:",
        "desc": "Add or update code related to validation.",
    },
    {
        "type": "chore",
        "icon": GitmojiEnum.CHORE,
        "code": ":broom:",
        "desc": "Commit changes related to miscelaneous chores.",
    },
    {
        "type": "squash",
        "icon": GitmojiEnum.SQUASH,
        "code": ":point_down:",
        "desc": "Squash commits.",
    },
    {
        "type": "fixup",
        "icon": GitmojiEnum.FIXUP,
        "code": ":dotted_line_face:",
        "desc": "Fixup commits.",
    },
]
