name: Python package

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "**"
    types: [opened, synchronize, reopened]
  create:
    branches:
      - "**"

jobs:
  python-check:
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]
        platform: [ubuntu-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.platform }}
    defaults:
      run:
        shell: bash

    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/cache@v4
        id: cache
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ runner.os }}-python-${{ env.pythonLocation }}-${{ hashFiles('pyproject.toml') }}-root

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Install Dependencies
        run: uv sync --frozen

      - name: Lint
        run: ./scripts/lint.sh

      - name: Test
        run: ./scripts/test.sh

      - name: Upload coverage
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  bump-version:
    runs-on: ubuntu-latest
    needs: [python-check]
    if: |
      github.event_name == 'push' &&
      github.ref_name == 'main' &&
      github.ref_type == 'branch' &&
      !startsWith(github.event.head_commit.message, '🔖 bump(release):') &&
      !startsWith(github.event.head_commit.message, 'bump(release):')
    name: "Bump version and create changelog with commitizen"
    steps:
      - name: Checkout
        if: github.actor == 'dependabot[bot]'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ github.token }}
          submodules: recursive

      - name: Checkout
        if: github.actor != 'dependabot[bot]'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          submodules: recursive

      - name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          extra_requirements: "uv cz-conventional-gitmoji"
